version: "3.8"

services:
  db:
    image: postgres:15
    container_name: college-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: college_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  